Repository FOSS-Cell-GECPKD/pixelvibe, pull requests merged in 2021-05, with the labels that each got.

#153 Adjusting drop-down menu
  css/style.css
Labels: Level1, gssoc21

#168 Migration to Flask
  JS/app.js
  app.py
  css/style.css
  index.html
  requirements.txt
  static/JS/login.js
  static/android-chrome-192x192.png
  static/android-chrome-512x512.png
  static/apple-touch-icon.png
  static/assets/20210325_164428 pixelvibe.svg
  static/assets/favicon_pixelVibe.png
  static/assets/pixelVibe.gif
  static/assets/pixel_logo.jpg
  static/assets/pixel_logo.png
  static/css/loader.css
  static/css/login.css
  static/favicon-16x16.png
  static/favicon-32x32.png
  static/favicon.ico
  static/favicon_pixelVibe.png
  static/fonts/Wagnasty-webfont.woff
  static/fonts/comic_zine_ot-webfont.woff
  static/fonts/slkscr-webfont.woff
  static/mstile-150x150.png
  template/canvas.html
  template/loader.html
  template/login.html
  template/safari-pinned-tab.svg
  template/user_input.html
Labels: Level3, gssoc21

#214 Cool Show Password Feature in Login and SignUp
  static/JS/login.js
  template/login.html
Labels: Level3, gssoc21

#243 backEnd for Contact us
  .gitignore
  home/admin.py
  home/models.py
  home/urls.py
  home/views.py
  template/canvas.html
  template/contact.html
  template/homepage.html
Labels: Level3, gssoc21

#269 added new features in canvas.html file
  template/canvas.html
Labels: Level3, gssoc21

#282 added front-end Pipeline for password reset feature
  home/urls.py
  home/views.py
  template/forgot.html
  template/login_new.html
  template/otp.html
  template/passwordReset.html
Labels: Level3, gssoc21

#305 Sending contact us response to admin email
  home/views.py
Labels: Level3, gssoc21

#325 Security Feature : Email Alert
  home/views.py
Labels: Level3, gssoc21

#329 fixed the bug in alert
  template/base.html
Labels: Level2, gssoc21

#322 Added PEP8 Standards
  PEP8StandardGuide.md
  Pycodestyle.md
  Readme.md
Labels: Level2, gssoc21

#331 Add Darkmode to ContactUs page
  static/JS/darkmode.js
  template/contact.html
Labels: Level3, gssoc21

#352 confirmation email after changing passwords
  home/views.py
Labels: Level3, gssoc21

#388 SMTPA authentication bug not only in contact but in all pages
  home/views.py
Labels: Level3, gssoc21

#391 Proper spacing and padding in navbar on canvas page
  template/canvas.html
Labels: Level2, gssoc21
