Repository FOSS-Cell-GECPKD/pixelvibe, pull requests merged in 2021-03, with the labels that each got.

#24 Added a Pull Request Template
  .github/pull_request_template.md
Labels: Level1, gssoc21

#59 fixed grid-visibility
  index.html
Labels: Level2, gssoc21

#55 Unable to scroll and bottom padding #54
  css/style.css
  index.html
Labels: Level0, gssoc21

#66 Logo upload and folder rename
  assets/pixelVibe.gif
  assets/pixel_logo.jpg
  assets/pixel_logo.png
Labels: Level1, gssoc21

#80 Contrast Changed
  css/login.css
  login.html
Labels: Level2, gssoc21

#81 made the bulb in toggle button fixed
  css/login.css
Labels: Level2, gssoc21

#91 Added PNG of favicon to assets
  android-chrome-192x192.png
  android-chrome-512x512.png
  apple-touch-icon.png
  assets/favicon_pixelVibe.png
  browserconfig.xml
  favicon-16x16.png
  favicon-32x32.png
  favicon.ico
  mstile-150x150.png
  safari-pinned-tab.svg
  site.webmanifest
Labels: Level1, gssoc21
